// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabalhoFinalDWEB2026.Data;

#nullable disable

namespace TrabalhoFinalDWEB2026.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrabalhoFinalDWEB2026.Models.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("TrabalhoFinalDWEB2026.Models.MyUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("MyUsers");

                    b.HasDiscriminator<string>("UserType").HasValue("MyUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TrabalhoFinalDWEB2026.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("MyUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MyUserId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("TrabalhoFinalDWEB2026.Models.ReceitaMedicamento", b =>
                {
                    b.Property<int>("ReceitaId")
                        .HasColumnType("int");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ReceitaId", "MedicamentoId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("ReceitaMedicamentos");
                });

            modelBuilder.Entity("TrabalhoFinalDWEB2026.Models.Doutor", b =>
                {
                    b.HasBaseType("TrabalhoFinalDWEB2026.Models.MyUser");

                    b.HasDiscriminator().HasValue("Doutor");
                });

            modelBuilder.Entity("TrabalhoFinalDWEB2026.Models.Farmaceuta", b =>
                {
                    b.HasBaseType("TrabalhoFinalDWEB2026.Models.MyUser");

                    b.HasDiscriminator().HasValue("Farmaceuta");
                });

            modelBuilder.Entity("TrabalhoFinalDWEB2026.Models.Receita", b =>
                {
                    b.HasOne("TrabalhoFinalDWEB2026.Models.Doutor", "Doctor")
                        .WithMany("ReceitasGiven")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrabalhoFinalDWEB2026.Models.MyUser", "MyUser")
                        .WithMany("Receitas")
                        .HasForeignKey("MyUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("MyUser");
                });

            modelBuilder.Entity("TrabalhoFinalDWEB2026.Models.ReceitaMedicamento", b =>
                {
                    b.HasOne("TrabalhoFinalDWEB2026.Models.Medicamento", "Medicamento")
                        .WithMany("ReceitaMedicamentos")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrabalhoFinalDWEB2026.Models.Receita", "Receita")
                        .WithMany("ReceitaMedicamentos")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("TrabalhoFinalDWEB2026.Models.Medicamento", b =>
                {
                    b.Navigation("ReceitaMedicamentos");
                });

            modelBuilder.Entity("TrabalhoFinalDWEB2026.Models.MyUser", b =>
                {
                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("TrabalhoFinalDWEB2026.Models.Receita", b =>
                {
                    b.Navigation("ReceitaMedicamentos");
                });

            modelBuilder.Entity("TrabalhoFinalDWEB2026.Models.Doutor", b =>
                {
                    b.Navigation("ReceitasGiven");
                });
#pragma warning restore 612, 618
        }
    }
}
